export const accountingData = [
  {
    companyId: 101,
    companyName: "Premium Travel Co.",
    info: "THB 23 560",
    routesByDate: [
      {
        id: 201,
        date: "01 May, 2025",
        info: "102 people",
        routes: [
          {
            id: 19876789,
            route: "istanbul-bartın",
            info: "50 people",
            capacity: 20,
            filled: 14,
            cashOnTour: 2,
            pickUp: 13,
            checkIn: 5,
            passengers: [
              {
                id: 1,
                name: "Hakan Kızılkaya",
                info: "4 people",
                cashOnTour: true,
                pickUp: true,
                checkIn: true,
              },
              {
                id: 2,
                name: "Ali İsmail",
                info: "3 people",
                cashOnTour: false,
                pickUp: true,
                checkIn: true,
              },
            ],
          },
          {
            id: 198787896789,
            route: "istanbul-adana",
            info: "34 people",
            capacity: 15,
            filled: 10,
            cashOnTour: 2,
            pickUp: 13,
            checkIn: 5,
            passengers: [
              {
                id: 3,
                name: "Rüstem Ünlü",
                cashOnTour: true,
                pickUp: true,
                checkIn: false,
                info: "12 people",
              },
            ],
          },
        ],
      },
      {
        id: 202,
        date: "02 May, 2025",
        info: "50 people",
        routes: [
          {
            id: 3,
            route: "istanbul- küthaya",
            info: "THB 23 560",
            capacity: 12,
            filled: 12,
            cashOnTour: 2,
            pickUp: 13,
            checkIn: 5,
            passengers: [
              {
                id: 4,
                name: "Ali Faysal",
                cashOnTour: false,
                pickUp: false,
                checkIn: false,
                info: "20 people",
              },
              {
                id: 5,
                name: "Hakan Kızılkaya",
                cashOnTour: true,
                pickUp: true,
                checkIn: true,
                info: "12 people",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    companyId: 102,
    companyName: "Elite Tours Ltd.",
    info: "THB 23 560",
    routesByDate: [
      {
        id: 203,
        date: "03 May, 2025",
        info: "34 people",
        routes: [
          {
            id: 198798786789,
            route: "istanbul- izmir",
            info: "16 people",
            capacity: 20,
            filled: 14,
            cashOnTour: 2,
            pickUp: 13,
            checkIn: 5,
            passengers: [
              {
                id: 89,
                name: "Semanur Arslan",
                cashOnTour: true,
                pickUp: true,
                checkIn: true,
                info: "24 people",
              },
              {
                id: 290,
                name: "Irmak Demir",
                cashOnTour: false,
                pickUp: true,
                checkIn: true,
                info: "5 people",
              },
            ],
          },
          {
            id: 19878798896789,
            route: "istanbul- amasya",
            info: "10 people",
            capacity: 15,
            filled: 10,
            cashOnTour: 2,
            pickUp: 13,
            checkIn: 5,
            passengers: [
              {
                id: 40,
                name: "Veli Koc",
                cashOnTour: true,
                pickUp: true,
                checkIn: false,
                info: "13 people",
              },
              {
                id: 41,
                name: "Ali Altay",
                cashOnTour: true,
                pickUp: true,
                checkIn: false,
                info: "12 people",
              },
            ],
          },
        ],
      },
    ],
  },
];
